fixed the issue where the original name of a node would be truncated when the name was too long.
nuttyartist/notes pull request #728
Opened 2024-11-21 01:55 UTC by 1250890838

fixed #647

2024-11-21 05:58 UTC, nuttyartist commented
@1250890838 Thanks a lot, it works well (:

2024-11-21 06:00 UTC, nuttyartist approved these changes

2024-11-21 18:08 UTC, zjeffer requested changes

2024-11-21 18:08 UTC, zjeffer commented on src/elidedlabel.cpp
> +    : QLabel(text, parent, f), defaultType(Qt::ElideRight), eliding(false), original("")
Can you fix the warning?

```
In file included from /src/src/elidedlabel.cpp:1:
/src/src/elidedlabel.h: In constructor 'ElidedLabel::ElidedLabel(const QString&, QWidget*, Qt::WindowFlags)':
/src/src/elidedlabel.h:26:10: warning: 'ElidedLabel::eliding' will be initialized after [-Wreorder]
   26 |     bool eliding;
      |          ^~~~~~~
/src/src/elidedlabel.h:24:13: warning:   'QString ElidedLabel::original' [-Wreorder]
   24 |     QString original;
      |             ^~~~~~~~
/src/src/elidedlabel.cpp:8:1: warning:   when initialized here [-Wreorder]
    8 | ElidedLabel::ElidedLabel(const QString &text, QWidget *parent, Qt::WindowFlags f)
      | ^~~~~~~~~~~
```

2024-11-21 23:53 UTC, 1250890838 commented
ok,i have fixed it.

2024-11-22 00:37 UTC, guihkx approved these changes
Also confirming the issue is fixed. Thanks!

2024-11-22 00:39 UTC, merged